### ISSUE TITLE
음악생성 모델 API 서버 GPU Out of memory 이슈

### ISSUE THREAD

**Issue by MuHyeonSon** [boostcampaitech5/level3_nlp_finalproject-nlp-01#15]
## 😀 작업 내용
-   현재 음악생성 모델 API 서버에 음악생성 요청을 받을 때 마다 GPU Memory-Usage가 증가하는 현상이 관찰되었으며, 결과적으로 CUDA Out of Memory 에러가 발생하여 음악을 생성하지 못하는 문제가 발견됨. 
    ![image](https://github.com/boostcampaitech5/level3_nlp_finalproject-nlp-01/assets/93263215/0d6b2f43-5a72-4b28-8b57-4b9a428df857)

-  numba 패키지를 이용하여 GPU 전용 메모리의 초기화가 되도록 코드 추가.
    ![image](https://github.com/boostcampaitech5/level3_nlp_finalproject-nlp-01/assets/93263215/fbec2cbe-ad06-42c3-88c9-180c21297c28)
    GPU 메모리 초기화 코드를 추가한 뒤, 웹페이지에서 음악생성 요청 진행.
    ![image](https://github.com/boostcampaitech5/level3_nlp_finalproject-nlp-01/assets/93263215/e7927cce-59e9-4b96-81d3-287cb2d5ee31)
    음악생성이 정상적으로 이루어졌고, nvidia-smi로 GPU Memory-Usage를 확인하였을 때, 잘 초기화가 된 것이 확인되었음.

## 🙉 참고
-   https://gilforce.com/gpu-%EB%A9%94%EB%AA%A8%EB%A6%AC-%EC%82%AC%EC%9A%A9%EB%9F%89-%EC%B4%88%EA%B8%B0%ED%99%94-%EB%B0%A9%EB%B2%95/
- https://velog.io/@claude_ssim/NVIDIA-GPU-%EB%B3%B4%EB%8A%94%EB%B2%95nvidia-smi

**Comment by Jiwonii97** [comment]
### 7/25 이슈
이슈 상태 : 문제 해결
원인 : GPU 캐시 메모리를 비우지 못함
해결 방법 : `torch.cuda.empty_cache()` 를 통한 cache 제거
